### ISSUE TITLE
Allow using external libraries to represent the `.amount` property

### ISSUE THREAD

**Issue by scotttrinh** [sarahdayan/dinero.js#18]
As a user of a library like dinero.js, it would be helpful to be able to use some library to hold the `.amount` property that supports very large integers, since we will be able to store extra precision soon by adding additional powers-of-ten to the `.amount`. That means the chances of hitting the minimum or maximum safe integer are that much easier.

I'm picturing an API similar to this one, using the [`big-integer`](https://github.com/peterolson/BigInteger.js) library as my example here:

```js
const BitIntCalculator = {
  add(a, b) => a.add(b),
  subtract(a, b) => a.subtract(b),
  divide(a, b) => {
    // Drats! big-integer requires the divisor to be an integer!
    return a.divide(Math.floor(b));
  },
  multiply(a, b) => {
    // Drats! big-integer requires both factors to be integers!
    return a.multiply(Math.floor(b));
  },
  modulo(a, b) => a.mod(b),
  round(a) => a
};
const bigIntDinero = amount => Dinero({ amount: bigInt(amount), calculator: BigIntCalculator });
const d = bigIntDinero(1e10);
```

You can probably already spot a few issues, but the one I want to point out right now is:

Most integer libraries do integer division and multiplication, which doesn't allow for rounding modes, etc. Perhaps that is fine since you're getting additional precision anyway, but it means we can't use `ROUNDING_MODE`s in these cases. At the very least, a documentation woe.

Any thoughts about the interface as it stands now? We could also do a shorthand like you suggested and have the calculator just be strings that are   mapped to methods on the `a` parameter like:

```js
const BitIntCalculator = {
  add: 'add',
  subtract: 'subtract',
  divide: 'divide',
  multiply: 'multiply',
  modulo: 'mod',
  round(a) => a
};
```

**Comment by sarahdayan** [comment]
If one decides to plug their own big number library, they're making a choice—which may come with drawbacks. So if a big number library doesn't let you divide by anything else than integers, then you need to be aware that it's a limitation and some arguments won't have any effect.

This will definitely need to be in the docs though.

One thing to keep in mind is that this integration is probably not here to stay: when the new [BigInt primitive](https://developers.google.com/web/updates/2018/05/bigint) becomes an ECMAScript standard and gets polyfills, we'll have to deprecate it. Only mentioning it so we don't get too carried away and simply provide an override for people who need big numbers now.

Strings are a good idea to indicate a similar interface: if your big number library has an `add` method that takes two arguments and returns the sum of these two, then it's a match, you can specify it as a string. Else, you can provide your own method, which will bridge between Dinero and your big number library.

We could use the `settings` service to set this up, possibly a new `Custom` object, and then have something like:

```js
Dinero.calculator({
  name: 'NamespaceOfTheLibrary',
  interface: { /* mappings here */ }
})
```

Now there's the whole thing of how to inject this custom dependency in a way that works in every environment (compiles well with Rollup) and with unit tests. This might be trivial but I don't want to speak too fast.

**Comment by scotttrinh** [comment]
Wow, I had not heard of the `BigInt` primitive, but browsing [the spec](https://tc39.github.io/proposal-bigint/), it looks *very* cool. Stage 3 already!

I was hoping that we wouldn't *need* to deprecate it if all we really did was provide a way for users to specify a `calculator` and maybe a `toFormat` method. Supporting the actual value for `.amount` would just go from `amount: bigInt(10)` to `amount: 10n` once BigInt landed in all supported browsers.

I don't see any problem with keeping a configurable `calculator` and `toFormat`, but if we're worried about creating bloat or technical debt by keeping it around, I'd rather just maybe put this idea to the side for now. Looks like it is in Chrome already and Firefox is well on its way. That leaves waiting for Safari and Edge to catch up.

**Comment by sarahdayan** [comment]
Yes, the bloat is what I'm worried about. Once `BigInt` is up and running, chances are it will become the dedicated type for `amount` (unless the performances are drastically affected, in that case, we'll see) and it will make the BigNumber library connector obsolete. Therefore it would have to go, which means a breaking change.

Because you don't want to bump the major just for it, it would have to go either:

- when we shift to v2 if `BigInt` is ready by then
- when we shift to v3 if it's not, and be marked as deprecated as soon as `BigInt` lands. This case is likely in a distant future, and `BigInt` will most probably land in the meantime. This means v2 would likely have to carry some dead weight.

I'm worrying that this is going to require extensive work that will be painful to remove.

**Comment by scotttrinh** [comment]
Sorry to disappear from this convo. I'm totally down with putting the brakes on this plan for now and see if it comes up as an issue in the real-world before designing a pre-emptive solution.

**Comment by sarahdayan** [comment]
@scotttrinh Thanks for your work and understanding 🙂 I'm going to close this now, but let's monitor the evolution of `BigInt` and reopen this issue then.

**Comment by ralusek** [comment]
@sarahdayan any news on BigInt?
