### ISSUE TITLE
Rename hasCents() to hasSubUnits()

### ISSUE THREAD

**Issue by IDisposable** [sarahdayan/dinero.js#20]
`hasCents()` is misleading when dealing with other non-100ths currencies. Should really be called `hasSubUnits()` or `hasSubunits()` to be clearer in the relationship to the `toUnit()` method.

## Expected behavior

A new method `hasSubUnits()` should be added with the same _body_ as the current method 
```
return calculator.modulo(this.getAmount(), Math.pow(10, precision)) !== 0
```
The `hasCents()` should be deprecated and the body should be replaced with
```
return this.hasSubUnit();
```

**Comment by sarahdayan** [comment]
Good catch, thanks! This is a leftover of the codebase before adding the precision concept. I will create a new similar method with a better name and deprecate `hasCents()`, which will be removed in v2.
