### ISSUE TITLE
More flexible currency conversion

### ISSUE THREAD

**Issue by Nemmo** [sarahdayan/dinero.js#21]
Hi folks!

Really nice package! And..

It will be good to pass own promise function when calling `convert` method.

**Comment by sarahdayan** [comment]
Hey Nemmo, thank you for the support!

Can you tell me a bit more about your use case and the expected behavior?

**Comment by Nemmo** [comment]
For example I want to get the currency information from our database, or make a soap request instead of rest

**Comment by sarahdayan** [comment]
Oh, I see. This would involve letting people create their own `getExchangeRate` method and pass it on. I can't promise it will happen for now but I'll keep the issue open in case someone wants to PR this and/or for me later.

In the meantime, I would suggest creating your own method around Dinero and the Calculator service.

**Comment by Roms1383** [comment]
Actually +1 👍  for this feature request, that would be cool especially since in some app the _rate_ is loaded once and cached for a certain duration, reducing the number of HTTP requests when using this method repeatedly.
If I can suggest, it would be cool to allow for an alternative to `options.endpoint` by specifying a custom`Promise` which is expected to produce the same output, parseable through the existing `options.propertyPath`.

**Comment by Roms1383** [comment]
```js
convert(currency, options) {
      options = Object.assign({}, globalExchangeRatesApi, options)
      // console.log(`options\n${JSON.stringify(options, null, 2)}`)
      return (options.endpoint instanceof Function
      ? options.endpoint.constructor.name === 'AsyncFunction' // can probably be improved
        ? options.endpoint(options)
        : Promise.resolve(options.endpoint(options))
      : CurrencyConverter(options).getExchangeRate(this.getCurrency(), currency))
        .then(rate => {
          assert(
            !isUndefined(rate),
            new TypeError(
              `No rate was found for the destination currency "${currency}".`
            )
          )
          return create.call(this, {
            amount: calculator.round(
              calculator.multiply(this.getAmount(), parseFloat(rate)),
              options.roundingMode
            ),
            currency
          })
        })
        .catch(console.error)
    }
```

**Comment by james-ff** [comment]
This would be great for my use case too, I'm using primarily GraphQL endpoints, and at the time of conversions I have the rates in data form and just need to pass them in. At the moment it looks like I have to spin up a REST api to be able to serve those in. Would be great if the JSON could be passed in directly. Have I missed a way to do that currently?

**Comment by sarahdayan** [comment]
So I think this could be made possible rather simply and without breaking changes by changing `CurrencyConverter.getExchangeRate` a bit.

Right now, I can see passing an option like `customRates` that would be a custom promise. If this is defined, `getExchangeRate` resolves it; else it does what it currently does.

Will start fiddling with it!

**Comment by sarahdayan** [comment]
@Roms1383 @james-ff Just opened a PR for it so you could get a look, I'm interested in your feedback before I merge it: https://github.com/sarahdayan/dinero.js/pull/49

**Comment by james-ff** [comment]
Looks good to me!

Is `propertyPath: 'rates.{{to}}'` required, or optional if the default object structure is used? Either way is ok, just curious.

**Comment by sarahdayan** [comment]
@james-ff There currently is not default structure, one always has to provide a `propertyPath`.

**Comment by sarahdayan** [comment]
@james-ff Just pushed the change 🔥
