### ISSUE TITLE
Suggestion on instance creation

### ISSUE THREAD

**Issue by vasilich6107** [sarahdayan/dinero.js#26]
Hi! Thanks for the great component.
I have two little suggestions)

1. Is it possible to have simplified alias to create Dinero instance
` Dinero(123) ` this will be useful in case if locale settings are controlled by some kind of i18n module.

2. It would be great to have possibility to distinguish `Dinero` object like
`if(money instanceof Dinero)`

Thanks a lot)

**Comment by sarahdayan** [comment]
Hello! Thanks for the suggestions :)

1. If you need an alias, I suggest you create your own helper factory. Here's a naive implementation you can tailor to your needs:

```js
const DineroFactory = (amount = 0, currency = 'USD') => {
  const d = Dinero({ amount, currency })
  // some logic
  return d
}
```

You could import your locale module and add some logic inside the factory.

2. Dinero.js doesn't use a constructor (you don't instantiate objects with the `new` keyword) so you can't use `instanceof` with it. You can still duck type:

```js
const d = Dinero()
const amount = d.getAmount ? d.getAmount() : 0
```
