### ISSUE TITLE
Can I extend currency by a new one?

### ISSUE THREAD

**Issue by AndyTyurin** [sarahdayan/dinero.js#27]
**I would to extend currency by new one – gaming currency**, but also I would like to use EUR, USD and other.

I didn't find API or docs about, so my question is it possible to accomplish?

**Comment by sarahdayan** [comment]
Hi Andy! There currently is no support for fantasy currencies, only [ISO 4217 currency codes](https://en.wikipedia.org/wiki/ISO_4217#Active_codes).

You can still create objects with any ISO 4217 currency codes:

```js
const d_dollar = Dinero({ currency: 'USD' }) // uses dDollars
const d_euro = Dinero({ currency: 'EUR' }) // uses Euros
```

If you want, you can also [convert a Dinero](https://sarahdayan.github.io/dinero.js/module-Dinero.html#~convert) object into another currency.

**Comment by AndyTyurin** [comment]
I can't exactly say "fantasy", but crypto currency.  Anyway, thank you, answer clear to me.
