### ISSUE TITLE
not support cny?

### ISSUE THREAD

**Issue by lilianjin** [sarahdayan/dinero.js#32]
## Expected behavior

```js
return Dinero({
			amount: amount * 1000,
			currency: 'CNY'
		})
		.toFormat('RMB 0,0.00')
```
## Actual behavior

Do not show

**Comment by sarahdayan** [comment]
The `toFormat` is intended to be used with a mask, not the destination currency you want to display the object into, [as stated in the docs](https://sarahdayan.github.io/dinero.js/module-Dinero.html#~toFormat).

If you want to display the object in `CNY`, you need to do:

```js
Dinero({
  amount: 1000,
  currency: 'CNY'
}).toFormat('USD0,0.00') // returns 'CNY 10.00' (may vary depending on `toLocaleString` implementation on the end browser)
```

If you want to display it into another currency, you need to [convert it first](https://sarahdayan.github.io/dinero.js/module-Dinero.html#~convert), then display it.

**Comment by lilianjin** [comment]
@sarahdayan thank, I also found a way to use this.
