### ISSUE TITLE
Support for displaying both symbol and currency code using toFormat

### ISSUE THREAD

**Issue by neemski** [sarahdayan/dinero.js#38]
Hello! I'm wondering if you could add support for Dinero generating a formatted currency string which displays both the currency code and the symbol? For example:

## Expected behavior
```js
Dinero({ amount: 40, currency: 'USD'}).setLocale('en-US').toFormat('USD$0,0.00');

>> "$0.40 USD"
```

```js
Dinero({ amount: 40, currency: 'CAD'}).setLocale('en-CA').toFormat('USD$0,0.00');

>> "$0.40 CAD"
```

```js
Dinero({ amount: 40, currency: 'CAD'}).setLocale('fr-CA').toFormat('USD$0,0.00')
>> "CAD 0,40 $"
```

```js
Dinero({ amount: 40, currency: 'EUR'}).setLocale('fr-FR').toFormat('USD$0,0.00')
>> "EUR 0,40 €"
```

or something.

**Comment by sarahdayan** [comment]
Hi @neemski ! Right now, [`toFormat` is syntactic sugar on top of `Number.toLocaleString()`](https://sarahdayan.github.io/dinero.js/module-Dinero.html#~toFormat), which means that it controls the output. This allows the library not to have to carry heavy internationalization files.

To achieve what you want without having to write a currency code map yourself, you could use [Dinero.toUnit](https://sarahdayan.github.io/dinero.js/module-Dinero.html#~toUnit) or [Dinero.toRoundedUnit](https://sarahdayan.github.io/dinero.js/module-Dinero.html#~toRoundedUnit) with [Intl.Numberformat.prototype.formatToParts()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat/formatToParts#Examples) to split the output and reformat it as you see fit.

Depending on the browser support for this feature, I might use it in v2. In the meantime, if the current support is good enough for you, I would recommend building your own helper with this.
