### ISSUE TITLE
How to use toFormat() with fractions of a penny?

### ISSUE THREAD

**Issue by kahlan88** [sarahdayan/dinero.js#48]
**Describe the bug**

Everything seems fine when using precision of 2, currency of GBP. 

**To reproduce**

`const val = Dinero({ amount: 10.125, currency: 'GBP', precision: 3 })`

Followed by:
`val.toFormat()`

**Expected behavior**

Displays `£10.125`

**Actual behaviour**

Displays `£10.13`, which is a rounded value and the precision is ignored.
(The same happens when provided `currency: 'YQD'`)

My understanding of the docs was that `toFormat()` should work with any precision? Or have I missed anything? Does it depend on currency provided? (It does work with `toFormat('$0,0.000')`.

**Comment by sarahdayan** [comment]
Hi @kahlan88, are you sure of the reproducing steps? You cannot pass a float as your Dinero amount, it throws a `TypeError`. I'll assume you meant `10125`, but correct me if I'm wrong.

The `toFormat` method does work with any precision, but it doesn't automatically outputs a number of fractional units equal to `precision`. You have to specify it yourself.

The default format is `'$0,0.00'` as specified in [the docs](https://sarahdayan.github.io/dinero.js/module-Dinero.html#~toFormat). If you want to display 3 fractional units, you indeed need to explicitly specify it.

```js
const val = Dinero({ amount: 10.125, currency: 'GBP', precision: 3 })

val.toFormat('$0,0.000') // "£10.125"
```
