### ISSUE TITLE
Support formatting a string that represents cents only

### ISSUE THREAD

**Issue by jestanoff** [sarahdayan/dinero.js#51]
I would like the `toFormat` to be able to represent a price in cents only.

When a price is less than an amount of 100 units it should be formatted as:
  ```59¢```  which according to the API should represent Dinero({ amount: 59, currency: 'USD' })

I imagine `toFormat` would accepts a string like:
```
Dinero({ amount: 59, currency: 'USD' }).toFormat('0c');
// returns '59¢'
```

Look at the example on this link, the price is in pounds but the logic is still the same: https://www.waitrose.com/ecom/products/essential-waitrose-semi-skimmed-milk-17-fat-2-pints/053448-26749-26750

**Comment by sarahdayan** [comment]
Hi @jestanoff and thanks for this suggestion. This is a good one!

For now, Dinero is relying on [Number.prototype.toLocaleString](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Number/toLocaleString), which as far as I know doesn't provide a way to represent amounts differently than with the currency symbol itself. You can read more about why I'm considering to move away from this API (and let people use it directly if they want to) in [this issue](https://github.com/sarahdayan/dinero.js/issues/36).

For now, I would recommend creating your own helper. A hint to start would be to compare the precision of your object to the number of digits of the amount (be mindful of negative numbers).
If the former is greater than or equal to the second, then you're in a case where you want to format using the sub-unit notation, which you can do by using `Dinero.getAmount` and concatenate it with the symbol of your choice.
