### ISSUE TITLE
convertPrecision(0) produces TypeError after divide/multiply

### ISSUE THREAD

**Issue by rjoo** [sarahdayan/dinero.js#53]
**Describe the bug**

.convertPrecision(0) produces TypeError

**To reproduce**

````
Dinero({
  amount: 22200,
  precision: 2
}).divide(1.5555555).convertPrecision(0);
````
**Expected behavior**

No TypeError as `0` is an integer.

**Additional context**
Just scratching my head on this one, this works fine:

````
Dinero({
  amount: 22200,
  precision: 2
}).divide(1.5).convertPrecision(0);
````

**Comment by sarahdayan** [comment]
Thanks for opening this @rjoo, that's a bug. It comes from the fact that there's no rounding in `convertPrecision`. I'll PR a fix asap.
