### ISSUE TITLE
Minimum and Maximum from an array of dinero instances

### ISSUE THREAD

**Issue by jotaoncode** [sarahdayan/dinero.js#60]
**Is your feature request related to a problem? Please describe.**

I find more declarative and intuitive to make the library resolve the Maximum / Minimum of several instances of Dinero.

**Describe the solution you'd like**

```
const dinero1 = new Dinero({amount: 50, currency: 'EUR'});
const dinero2 = new Dinero({amount: 100, currency: 'EUR'});
const maxDinero = Dinero.max(dinero1, dinero2);  // === dinero2

const dinero3 = new Dinero({amount: 50, currency: 'EUR'});
const dinero4 = new Dinero({amount: 100, currency: 'EUR'});
const minDinero = Dinero.min(dinero3, dinero4); // === dinero3 
```

**Describe alternatives you've considered**

This case could be solved as static method solution of the class Dinero.

Another solution to the one in the section before, when no dinero instance is provided, could be.
`
Dinero.max('EUR', 20, 30, 40, 10, 100); // returns new Dinero({amount: 100, currency: 'EUR'});
`

**Additional context**

I was going to provide a PR, but read in the contribution guidelines that new features the following statement:

Develop features that aren't in the scope of the library (if not sure, ask before you code).

If you consider this as a good change I will gladly provide this feature.

Warm regards and thx for the help with this library.

**Comment by sarahdayan** [comment]
Hey @jotaoncode, I think this is a great idea , and it would work great as static methods 🙂 Feel free to PR this!

**Comment by jotaoncode** [comment]
Hello, here is the PR https://github.com/sarahdayan/dinero.js/pull/61/commits it says that it is ready to be squashed, but I am not sure if it is going to be squashed by the tool or if it is something I should do. this is the squashed commit https://github.com/sarahdayan/dinero.js/pull/61/commits/238a7801bf87c3c2b5789f5e103e118645038698 but I don't see the PR green in the semantic PR tool.

**Comment by sarahdayan** [comment]
@jotaoncode Commits should be following the Angular style guide (there's a [CLI tool](https://github.com/sarahdayan/dinero.js/blob/develop/CONTRIBUTING.md#commit-messages) in the project to help with that).

Also, please make sure [you don't commit the documentation when you build it](https://github.com/sarahdayan/dinero.js/blob/develop/CONTRIBUTING.md#docs). It gets compiled from the doclets during build time.

**Comment by jotaoncode** [comment]
@sarahdayan I am learning a lot from all this, here is the PR https://github.com/sarahdayan/dinero.js/pull/63 with the improvement.

thanks for your patience, I hope this time it is everything as you expect, otherwise please let me know and I take a look into it.

Warm regards,

Juan

**Comment by sarahdayan** [comment]
@jotaoncode Glad that you're having fun and learning with this 🙂 This is a really nice contribution, I just reviewed.

**Comment by jotaoncode** [comment]
@sarahdayan thanks for the review, I just added those fixes. I think the workflow I learnt from here with semantic releases + commitizen + husky and also the git rebase - squash brings a lot of light to me. Any further changes you need I will be glad to work on it :)

Warm regards,

Juan
