### ISSUE TITLE
From Localized String to Number 

### ISSUE THREAD

**Issue by firaskrichi** [sarahdayan/dinero.js#62]
Is there a way to format a string back to a Number. 

I'm using Cleave.js where the user inputs the amount in a German locale for example : `20,99` and I want to be able to convert it to a Number 20.99 to do some calculations and display the localized string back. 

Thank you!

**Comment by sarahdayan** [comment]
Hey @firaskrichi, there's a [project](https://github.com/sarahdayan/dinero.js/issues/58) on making a factory to create Dinero objects from floats; however, parsing localized strings is a whole other ordeal and would likely happen in v2 if at all.

In the meantime, I suggest you create your own utility, like this:

```js
const fromGermanLocalized = str => Dinero({
  amount: parseFloat(str.replace(',', '.')) * 100,
  currency: 'EUR'
})
```

Closing this for now, but keeping it in mind for when I start v2 🙂

**Comment by sarahdayan** [comment]
[project](url)
