### ISSUE TITLE
Documentation request: which browsers require the polyfills?

### ISSUE THREAD

**Issue by stamminator** [sarahdayan/dinero.js#68]
It isn't clear, unless I've missed it, which browser versions work with the un-polyfilled dinero.js. I'd love to know whether or not I can use the smaller version, but until I know the browser compatibility, I have to play it safe and serve up the poly-saturated version.

**Comment by sarahdayan** [comment]
Hi @stamminator, the [polyfilled version](https://github.com/sarahdayan/dinero.js/blob/develop/src/dinero-polyfilled.js) imports the following fills:

```
import 'core-js/fn/array/every'
import 'core-js/fn/array/find-index'
import 'core-js/fn/array/find'
import 'core-js/fn/array/keys'
import 'core-js/fn/object/assign'
import 'core-js/fn/object/entries'
import 'core-js/fn/number/is-integer'
import 'core-js/fn/math/sign'
import 'core-js/fn/promise'
```

Browser support varies, so you'll need to look up [MDN](https://developer.mozilla.org/fr/) or [caniuse](https://caniuse.com/) for each to see if they are compatible with the browsers you need to support.

I'm moving away from including a filled version in v2, as not everyone might need the same, or you might already have them in your project, etc. I would recommend, if you're worried about filesize,  to go with the non-filled version and import the polyfills you need (from the list above) through [Polyfill.io](https://polyfill.io/v3/) :)
