### ISSUE TITLE
toFormat() not working on android in React Native

### ISSUE THREAD

**Issue by shamilihsan** [sarahdayan/dinero.js#88]
I installed this library on a React Native 0.60 project

`Dinero({ amount: 10000 }).toFormat('0,0.00')`

The above code shows a formatted value of `100.00` on iOS but on android it displays `100`.

But if I go to the developer menu and enable **Debug JS Remotely** it displays the correct formatted value i.e. `100.00`. Really confused on how this happens.

I ran a release build and the issue still persists on the android platform so really stuck here.

Hope someone can help me out

**Comment by sarahdayan** [comment]
Hi @shamilihsan!

As explained [in the documentation](https://sarahdayan.github.io/dinero.js/module-Dinero.html#~toFormat), `toFormat` wraps around [Number.prototype.toLocaleString](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Number/toLocaleString). For that reason, **format will vary depending on how it's implemented in the end user's environment**.

In v2, `toFormat` will no longer use this native API to avoid this problem. In the mean time, if you need exactly the same formatting everywhere, I recommend doing it by hand.

Here's how I would do it:

```js
const currencySymbols = {
  EUR: "€",
  USD: "$"
  // ...
};

function toFormatSafe(d) {
  const [units, subunits] = d
    .toRoundedUnit(2)
    .toString()
    .split(".");
  const currency = currencySymbols[d.getCurrency()];
  const stringified = subunits
    ? [units, subunits.padEnd(2, "0")].join(".")
    : [units, "00"].join(".");

  return `${stringified} ${currency}`;
}
```

**Comment by sarahdayan** [comment]
Also, this might help: https://github.com/sarahdayan/dinero.js/pull/86

**Comment by shamilihsan** [comment]
Thanks for the quick response!
Will have a look at these
